set number
set relativenumber
set autoindent
set smartindent
set linebreak
set incsearch
set hlsearch
set undofile
syntax on
set cursorline
set showmatch
set clipboard=unnamedplus
set wildmenu
set wildmode=longest:full,full
set spell
set tabstop=4
set shiftwidth=4
set expandtab
set mouse=a
